// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_map.proto

package org.apache.flink.formats.protobuf.testproto;

public interface MapTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.flink.formats.protobuf.proto.MapTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 a = 1;</code>
   * @return Whether the a field is set.
   */
  boolean hasA();
  /**
   * <code>optional int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>map&lt;string, string&gt; map1 = 2;</code>
   */
  int getMap1Count();
  /**
   * <code>map&lt;string, string&gt; map1 = 2;</code>
   */
  boolean containsMap1(
      String key);
  /**
   * Use {@link #getMap1Map()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getMap1();
  /**
   * <code>map&lt;string, string&gt; map1 = 2;</code>
   */
  java.util.Map<String, String>
  getMap1Map();
  /**
   * <code>map&lt;string, string&gt; map1 = 2;</code>
   */

  String getMap1OrDefault(
      String key,
      String defaultValue);
  /**
   * <code>map&lt;string, string&gt; map1 = 2;</code>
   */

  String getMap1OrThrow(
      String key);

  /**
   * <code>map&lt;string, .org.apache.flink.formats.protobuf.proto.MapTest.InnerMessageTest&gt; map2 = 3;</code>
   */
  int getMap2Count();
  /**
   * <code>map&lt;string, .org.apache.flink.formats.protobuf.proto.MapTest.InnerMessageTest&gt; map2 = 3;</code>
   */
  boolean containsMap2(
      String key);
  /**
   * Use {@link #getMap2Map()} instead.
   */
  @Deprecated
  java.util.Map<String, MapTest.InnerMessageTest>
  getMap2();
  /**
   * <code>map&lt;string, .org.apache.flink.formats.protobuf.proto.MapTest.InnerMessageTest&gt; map2 = 3;</code>
   */
  java.util.Map<String, MapTest.InnerMessageTest>
  getMap2Map();
  /**
   * <code>map&lt;string, .org.apache.flink.formats.protobuf.proto.MapTest.InnerMessageTest&gt; map2 = 3;</code>
   */

  MapTest.InnerMessageTest getMap2OrDefault(
      String key,
      MapTest.InnerMessageTest defaultValue);
  /**
   * <code>map&lt;string, .org.apache.flink.formats.protobuf.proto.MapTest.InnerMessageTest&gt; map2 = 3;</code>
   */

  MapTest.InnerMessageTest getMap2OrThrow(
      String key);

  /**
   * <code>map&lt;string, bytes&gt; map3 = 4;</code>
   */
  int getMap3Count();
  /**
   * <code>map&lt;string, bytes&gt; map3 = 4;</code>
   */
  boolean containsMap3(
      String key);
  /**
   * Use {@link #getMap3Map()} instead.
   */
  @Deprecated
  java.util.Map<String, com.google.protobuf.ByteString>
  getMap3();
  /**
   * <code>map&lt;string, bytes&gt; map3 = 4;</code>
   */
  java.util.Map<String, com.google.protobuf.ByteString>
  getMap3Map();
  /**
   * <code>map&lt;string, bytes&gt; map3 = 4;</code>
   */

  com.google.protobuf.ByteString getMap3OrDefault(
      String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; map3 = 4;</code>
   */

  com.google.protobuf.ByteString getMap3OrThrow(
      String key);
}
